### Scratchwork notebook for aircraft performance calculator

In [2]:
import numpy as np
import scipy as sp
import tables_172S as tb
import performance_172S as pf

In [3]:
sfto_ground_roll

NameError: name 'sfto_ground_roll' is not defined

In [11]:
points = (weight_index, temperature_index, pressure_altitude_index)
points

(array([2550, 2400, 2200]),
 array([ 0, 10, 20, 30, 40]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000]))

In [12]:
point = np.array([2550, 0, 0])

In [33]:
sp.interpolate.interpn(points, sfto_ground_roll, point)

array([860.])

In [23]:
weight_index

array([2550, 2400, 2200])

In [19]:
lift_off_index

array([51, 48, 44])

In [27]:
# x-coordinates in index must be increasing order
np.interp(np.array(2550), weight_index[::-1], lift_off_index[::-1])

51.0

In [28]:
# x-coordinates in index must be increasing order
np.interp(np.array(2550), weight_index[::-1], speed_at_50_feet_index[::-1])

56.0

In [34]:
def get_short_field_takeoff_performance(
    pressure_altitude: float, weight: float, temperature: float
) -> float:
    """
    Compute the short field takeoff ground roll, distance at 50 ft obstacle, lift off speed, and speed at 50 ft
    given aircraft weight, pressure altitude in ft, and temperature in deg C.

    Return ground_roll, dist_50ft, lift_off_speed, speed_at_50ft
    """

    # Compute ground_roll
    points = (weight_index, temperature_index, pressure_altitude_index)
    point = np.array([weight, temperature, pressure_altitude])
    ground_roll = sp.interpolate.interpn(points, sfto_ground_roll, point)[0]

    # Compute dist_50ft
    # TODO add table!
    dist_50ft = 0

    # Compute lift_off_speed
    lift_off_speed = np.interp(
        np.array(weight), weight_index[::-1], lift_off_index[::-1]
    )

    # Compute lift_off_speed
    speed_at_50ft = np.interp(
        np.array(2550), weight_index[::-1], speed_at_50_feet_index[::-1]
    )

    return ground_roll, dist_50ft, lift_off_speed, speed_at_50ft

In [35]:
get_short_field_takeoff_performance(5045, 2350, 15)

(1257.5281249999998, 0, 47.0, 56.0)

In [8]:
210 % 180

30

In [10]:
import math

In [26]:
runway = 210
wind_dir = 180
wind_spd = 10
v_rot = 55

In [27]:
headwind_heading = (runway - 180) % 360
headwind_heading

30

In [13]:
v_rot * wind_spd * math.cos(math.pi * (runway % 180 - wind_dir) / 180)

-476.3139720814413

In [29]:
xwind_modifier = math.cos(math.pi * headwind_heading / 180)
xwind_modifier

0.8660254037844387

In [31]:
xwind_component = xwind_modifier * wind_spd
xwind_component

8.660254037844387

In [36]:
math.cos(math.pi / 3)

0.5000000000000001

In [38]:
30 / 90

0.3333333333333333

In [39]:
rad_conv = math.pi / 180

In [46]:
[10 * math.cos(rad_conv * dg) for dg in [30, 60, 90, 120]]

[8.660254037844387,
 5.000000000000001,
 6.123233995736766e-16,
 -4.999999999999998]

In [55]:
1333 / 1159

1.1501294219154443

In [57]:
runway_grade = 0.01
theta = math.tan(rad_conv * runway_grade)

In [59]:
1 / math.sin(theta)

5729.577922219411

In [62]:
np.arange(0, 10000, 1000, dtype=float)

array([   0., 1000., 2000., 3000., 4000., 5000., 6000., 7000., 8000.,
       9000.])