### Scratchwork notebook for aircraft performance calculator

In [1]:
import numpy as np
import scipy as sp
from tables_172S import *

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 5) + inhomogeneous part.

In [12]:
# SFTO index arrays
temp_index = np.array([0, 10, 20, 30, 40])
pressure_altitude_index = np.array([0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000])

In [10]:
# Ground roll table for 2550 pounds
sfto = np.array([
    [
        860,
        940,
        1025,
        1125,
        1235,
        1355,
        1495,
        1645,
        1820
    ],

    [
        925,
        1010,
        1110,
        1215,
        1335,
        1465,
        1615,
        1785,
        1970
    ],

    [
        995,
        1090,
        1195,
        1310,
        1440,
        1585,
        1745,
        1920,
        2120
    ],

    [
        1070,
        1170,
        1285,
        1410,
        1550,
        1705,
        1875,
        2065,
        2280
    ],

    [
        1150,
        1260,
        1380,
        1515,
        1660,
        1825,
        2010,
        2215,
        2450
    ]

]
)

In [11]:
sfto

array([[ 860,  940, 1025, 1125, 1235, 1355, 1495, 1645, 1820],
       [ 925, 1010, 1110, 1215, 1335, 1465, 1615, 1785, 1970],
       [ 995, 1090, 1195, 1310, 1440, 1585, 1745, 1920, 2120],
       [1070, 1170, 1285, 1410, 1550, 1705, 1875, 2065, 2280],
       [1150, 1260, 1380, 1515, 1660, 1825, 2010, 2215, 2450]])

In [20]:
points = (temp_index, pressure_altitude_index)
points

(array([ 0, 10, 20, 30, 40]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000]))

In [23]:
point = np.array([15, 2000])

In [24]:
sp.interpolate.interpn(points, sfto, point)

array([1152.5])