### Scratchwork notebook for aircraft performance calculator

In [1]:
import numpy as np
import scipy as sp
from tables_172S import *

In [2]:
sfto_ground_roll

array([[[ 860,  940, 1025, 1125, 1235, 1355, 1495, 1645, 1820],
        [ 925, 1010, 1110, 1215, 1335, 1465, 1615, 1785, 1970],
        [ 995, 1090, 1195, 1310, 1440, 1585, 1745, 1920, 2120],
        [1070, 1170, 1285, 1410, 1550, 1705, 1875, 2065, 2280],
        [1150, 1260, 1380, 1515, 1660, 1825, 2010, 2215, 2450]],

       [[ 745,  810,  885,  970, 1065, 1170, 1285, 1415, 1560],
        [ 800,  875,  955, 1050, 1150, 1265, 1390, 1530, 1690],
        [ 860,  940, 1030, 1130, 1240, 1360, 1500, 1650, 1815],
        [ 925, 1010, 1110, 1215, 1335, 1465, 1610, 1770, 1950],
        [ 995, 1085, 1190, 1305, 1430, 1570, 1725, 1900, 2095]],

       [[ 610,  665,  725,  795,  870,  955, 1050, 1150, 1270],
        [ 655,  720,  785,  860,  940, 1030, 1130, 1245, 1370],
        [ 705,  770,  845,  925, 1010, 1110, 1220, 1340, 1475],
        [ 760,  830,  905,  995, 1090, 1195, 1310, 1435, 1580],
        [ 815,  890,  975, 1065, 1165, 1275, 1400, 1540, 1695]]])

In [11]:
points = (weight_index, temperature_index, pressure_altitude_index)
points

(array([2550, 2400, 2200]),
 array([ 0, 10, 20, 30, 40]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000]))

In [12]:
point = np.array([2550, 0, 0])

In [33]:
sp.interpolate.interpn(points, sfto_ground_roll, point)

array([860.])

In [23]:
weight_index

array([2550, 2400, 2200])

In [19]:
lift_off_index

array([51, 48, 44])

In [27]:
# x-coordinates in index must be increasing order
np.interp(np.array(2550), weight_index[::-1], lift_off_index[::-1])

51.0

In [28]:
# x-coordinates in index must be increasing order
np.interp(np.array(2550), weight_index[::-1], speed_at_50_feet_index[::-1])

56.0

In [34]:
def get_short_field_takeoff_performance(pressure_altitude: float, weight: float, temperature: float) -> float:
    """
    Compute the short field takeoff ground roll, distance at 50 ft obstacle, lift off speed, and speed at 50 ft
    given aircraft weight, pressure altitude in ft, and temperature in deg C. 

    Return ground_roll, dist_50ft, lift_off_speed, speed_at_50ft
    """

    # Compute ground_roll
    points = (weight_index, temperature_index, pressure_altitude_index)
    point = np.array([weight, temperature, pressure_altitude])
    ground_roll = sp.interpolate.interpn(points, sfto_ground_roll, point)[0]

    # Compute dist_50ft
    # TODO add table!
    dist_50ft = 0

    # Compute lift_off_speed
    lift_off_speed = np.interp(np.array(weight), weight_index[::-1], lift_off_index[::-1])

    # Compute lift_off_speed
    speed_at_50ft = np.interp(np.array(2550), weight_index[::-1], speed_at_50_feet_index[::-1])

    return ground_roll, dist_50ft, lift_off_speed, speed_at_50ft

In [35]:
get_short_field_takeoff_performance(5045, 2350, 15)

(1257.5281249999998, 0, 47.0, 56.0)